base_url: "http://localhost:1234"
api_endpoint: "/v1/chat/completions"
content: "You are a friendly cycling coach.You always provide well-reasoned answers that are both correct and helpful."
temperature: 0.7
max_tokens: -1
stream: False
