app_name: "CadenceAI"
base_url: "0.0.0.0"
port: 8081
api_endpoint: "/v1/question"
model_path: "artifacts/zephyr-7b-beta.Q4_K_S.gguf"
content: "You are a friendly cycling coach. You always provide well-reasoned answers that are both correct and helpful."
temperature: 0.7
max_tokens: 100
stream: False
n_gpu_layers: 8

vision_model: "gemini-pro-vision"
vision_content: "What is this?"
vision_max_output_tokens: 2048
vision_temperature: 0.4
vision_top_p: 1
vision_top_k: 32
vision_stream: True
img_path: "artifacts/IMG_4109.jpg"
img_type: "image/jpeg"

