app_name: "CadenceAI"
base_url: "http://localhost"
port: 1234
api_endpoint: "/v1/chat/completions"
headers: { "Content-Type": "application/json" }
model_path: "artifacts/llama-2-7b-chat.Q2_K.gguf"
#model_path: "artifacts/zephyr-7b-beta.Q4_K_S.gguf"
content: "You are a friendly cycling coach. You always provide well-reasoned answers that are both correct and helpful."
temperature: 0.7
max_tokens: 100
stream: False

vision_model: "gemini-pro-vision"
vision_content: "What is this?"
vision_max_output_tokens: 2048
vision_temperature: 0.4
vision_top_p: 1
vision_top_k: 32
vision_stream: True
img_path: "artifacts/IMG_4107.jpg"
img_type: "image/jpeg"

